---
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
log:
  level: "debug"

authentication_backend:
  ldap:
    address: ldap://glauth.default.svc.cluster.local:389
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: "{{ .GLAUTH_BASE_DN }}"
    additional_users_dn: ou=people,ou=users
    users_filter: (&({username_attribute}={input})(objectClass=posixAccount))
    additional_groups_dn: ou=users
    groups_filter: (&(uniqueMember={dn})(objectClass=posixGroup))
    user: "{{ .GLAUTH_SEARCH_USER }}"
    password: "{{ .GLAUTH_SEARCH_PASSWORD_PLAIN }}"
    attributes:
      username: uid
      display_name: givenName
      group_name: ou
      mail: mail
      member_of: memberOf
  password_reset:
    disable: true
  refresh_interval: 1m

session:
  secret: "{{ .AUTHELIA_SESSION_SECRET }}"
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: "${SECRET_DOMAIN%.live}_session"
      domain: "${SECRET_DOMAIN}"
      authelia_url: "https://auth.${SECRET_DOMAIN}"
      default_redirection_url: "https://home.${SECRET_DOMAIN}"
  redis:
    database_index: 1
    host: dragonfly.database.svc.cluster.local

storage:
  encryption_key: "{{ .AUTHELIA_STORAGE_ENC_KEY }}"

notifier:
  disable_startup_check: false
  smtp:
    username: "{{ .SMTP_USER }}"
    password: "{{ .SMTP_PASS }}"
    address: "submissions://smtp.migadu.com:465"
    sender: "auth@${SECRET_DOMAIN}"
    startup_check_address: test@authelia.com
    subject: "[Authelia] {title}"
    timeout: 5s

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: false
  display_name: "Authelia"
  attestation_conveyance_preference: "indirect"
  user_verification: "preferred"
  timeout: "60s"

duo_api:
  disable: false
  hostname: "{{ .DUO_HOSTNAME }}"
  integration_key: "{{ .DUO_INTEGRATION_KEY }}"
  secret_key: "{{ .DUO_SECRET_KEY }}"
  enable_self_enrollment: true

access_control:
  default_policy: two_factor

  rules:
    - domain: "*.${SECRET_DOMAIN}"
      resources:
        - "^/api/v1/status$"
        - "^/web/index.html$"
        - "^/api/system/status$"
      policy: bypass

    - domain: "theme-park.${SECRET_DOMAIN}"
      resources:
        - "^/css/(addons|base)/.*\\.css$"
      policy: bypass

identity_validation:
  reset_password:
    jwt_secret: "{{ .AUTHELIA_JWT_RESET_SECRET }}"

identity_providers:
  oidc:
    hmac_secret: "{{ .AUTHELIA_HMAC_SECRET }}"
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    jwks:
      - key: |-
          {{- .AUTHELIA_JWKS_PRIV_KEY | nindent 10 }}
        algorithm: "RS256"
    clients:
      - client_id: "{{ .GRAFANA_OAUTH_CLIENT_ID }}"
        client_secret: "{{ .GRAFANA_OAUTH_CLIENT_SECRET_ENC }}"
        client_name: Grafana
        public: false
        require_pkce: true
        pkce_challenge_method: "S256"
        pre_configured_consent_duration: 1y
        scopes: [openid, profile, groups, email]
        redirect_uris: ["https://grafana.${SECRET_DOMAIN}/login/generic_oauth"]
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: "client_secret_basic"
      - client_id: "{{ .HEADLAMP_OAUTH_CLIENT_ID }}"
        client_secret: "{{ .HEADLAMP_OAUTH_CLIENT_SECRET_ENC }}"
        client_name: Headlamp
        public: false
        require_pkce: false
        pre_configured_consent_duration: 1y
        scopes: [openid, profile, groups, email]
        redirect_uris: ["https://headlamp.${SECRET_DOMAIN}/oidc-callback"]
        userinfo_signed_response_alg: none
        token_endpoint_auth_method: "client_secret_basic"