---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 1h

  chartRef:
    kind: OCIRepository
    name: minecraft

  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    fullnameOverride: *app

    podAnnotations:
      configmap.reloader.stakater.com/reload: "minecraft-pack-configs"

    resources:
      requests:
        memory: 512Mi
        cpu: 200m
      limits:
        cpu: 16
        memory: 20Gi

    minecraftServer:
      cheats: false
      difficulty: normal
      eula: "TRUE"
      gameMode: survival
      maxPlayers: 20
      onlineMode: true
      ops: "2535421636443049,2535410585100219"
      serverName: "FrenZone"
      texturepackRequired: true
      tickDistance: 6
      threads: 0
      viewDistance: 20
      whitelist: true
      whitelistUsers: BigWizWyatt,DJVelveeta69,HeavyBullets88,BlackafroTTV,MediumYoda,PwNpRo,eelllliiee8368,KeeKs026,JsmallTheFried,ElderSchnibs,HatiMoonPursuer,BigTonez00,Da Lupster,Pistol 414l,Myuh5852

      serviceType: LoadBalancer
      serverPort: 19132

      # renovate: datasource=custom.bedrock depName=MinecraftBedrockServer versioning=loose
      version: "1.21.102.1"

    extraEnv:
      TZ: ${TIMEZONE}

    persistence:
      labels: {}
      dataDir:
        enabled: true
        existingClaim: *app

    serviceAnnotations:
      lbipam.cilium.io/ips: "${MINECRAFT_IP}"

  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: minecraft-minecraft-bedrock
            patch: |
              - op: add
                path: /spec/template/spec/volumes/-
                value:
                  name: pack-configs
                  configMap:
                    name: minecraft-pack-configs
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: pack-configs
                  mountPath: /data/worlds/level/world_resource_packs.json
                  subPath: world_resource_packs.json
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: pack-configs
                  mountPath: /data/worlds/level/world_behavior_packs.json
                  subPath: world_behavior_packs.json
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts/-
                value:
                  name: pack-configs
                  mountPath: /data/valid_known_packs.json
                  subPath: valid_known_packs.json
