---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "${SECRET_DOMAIN//./-}-tls"
spec:
  externalSecretName: "${SECRET_DOMAIN//./-}-tls"
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            # - cert-manager
            - network
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 30s
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect
    target:
      name: "${SECRET_DOMAIN//./-}-tls"
      creationPolicy: Orphan
      template:
        engineVersion: v2
        type: kubernetes.io/tls
        metadata:
          annotations:
            cert-manager.io/alt-names: "*.${SECRET_DOMAIN},${SECRET_DOMAIN}"
            cert-manager.io/certificate-name: "${SECRET_DOMAIN//./-}"
            cert-manager.io/common-name: "${SECRET_DOMAIN}"
            cert-manager.io/ip-sans: ""
            cert-manager.io/issuer-group: ""
            cert-manager.io/issuer-kind: ClusterIssuer
            cert-manager.io/issuer-name: letsencrypt-production
            cert-manager.io/uri-sans: ""
          labels:
            controller.cert-manager.io/fao: "true"
    dataFrom:
      - extract:
          key: "${SECRET_DOMAIN//./-}-tls"
          decodingStrategy: Auto