- trash_ids:
    # Anime Misc
    - d2d7b8a9d39413da5f44054080e028a3 # v0
    - 273bd326df95955e1b6c26527d1df89b # v1
    - 228b8ee9aa0a609463efca874524a6b8 # v2
    - 0e5833d3af2cc5fa96a0c29cd4477feb # v3
    - 4fc15eeb8f2f9a749f918217d4234ad8 # v4

    # Anime Optional
    - b2550eb333d27b75833e25b8c2557b38 # 10bit
    - 026d5aadd1a6b4e550b134cb6c72b3ca # Uncensored

    # Anime Source Groups
    - 949c16fe0a8147f50ba82cc2df9411c9 # Anime BD Tier 01 (Top SeaDex Muxers)
    - ed7f1e315e000aef424a58517fa48727 # Anime BD Tier 02 (SeaDex Muxers)
    - 096e406c92baa713da4a72d88030b815 # Anime BD Tier 03 (SeaDex Muxers)
    - 30feba9da3030c5ed1e0f7d610bcadc4 # Anime BD Tier 04 (SeaDex Muxers)
    - 545a76b14ddc349b8b185a6344e28b04 # Anime BD Tier 05 (Remuxes)
    - 25d2afecab632b1582eaf03b63055f72 # Anime BD Tier 06 (FanSubs)
    - 0329044e3d9137b08502a9f84a7e58db # Anime BD Tier 07 (P2P/Scene)
    - c81bbfb47fed3d5a3ad027d077f889de # Anime BD Tier 08 (Mini Encodes)
    - e3515e519f3b1360cbfc17651944354c # Anime LQ Groups
    - b4a1b3d705159cdca36d71e57ca86871 # Anime Raws
    - e0014372773c8f0e1bef8824f00c7dc4 # Anime Web Tier 01 (Muxers)
    - 19180499de5ef2b84b6ec59aae444696 # Anime Web Tier 02 (Top FanSubs)
    - c27f2ae6a4e82373b0f1da094e2489ad # Anime Web Tier 03 (Official Subs)
    - 4fd5528a3a8024e6b49f9c67053ea5f3 # Anime Web Tier 04 (Official Subs)
    - 29c2a13d091144f63307e4a8ce963a39 # Anime Web Tier 05 (FanSubs)
    - dc262f88d74c651b12e9d90b39f6c753 # Anime Web Tier 06 (FanSubs)

    # Anime Streaming Services
    - a370d974bc7b80374de1d9ba7519760b # ABEMA
    - d54cd2bf1326287275b56bccedb72ee2 # ADN
    - 7dd31f3dee6d2ef8eeaa156e23c3857e # B-Global
    - 4c67ff059210182b59cdd41697b8cb08 # Bilibili
    - 3e0b26604165f463f3e8e192261e7284 # CR
    - 1284d18e693de8efe0fe7d6b3e0b9170 # FUNi
    - 570b03b3145a25011bf073274a407259 # HIDIVE
    - 44a8ee6403071dd7b8a3a8dd3fe8cb20 # VRV
    - e5e6405d439dcd1af90962538acd4fe0 # WKN

    # Asian Streaming Services
    - 7be9c0572d8cd4f81785dacf7e85985e # FOD
    - 4404ad44d87ccbb82746e180713112fb # HTSR
    - 86f8d3b8761de651aa355d46d5d8db3e # TVING
    - d100ea972d1af2150b65b1cffb80f6b5 # TVer
    - 0e99e7cc719a8a73b2668c3a0c3fe10c # U-NEXT
    - 93c9d1e566dca8b34d57f5efbbf85f28 # VIU

  quality_profiles:
    - name: Anime

# Dual Audio
- trash_ids:
    - 418f50b10f1907201b6cfdf881f467b7 # Anime Dual Audio
  quality_profiles:
    - name: Anime
      score: 2000

# Dubs Only
- trash_ids:
    - 9c14d194486c4014d422adc64092d794 # Dubs Only
  quality_profiles:
    - name: Anime
      score: 1900

# Only French Subs
- trash_ids:
    - 07a32f77690263bb9fda1842db7e273f # VOSTFR
  quality_profiles:
    - name: Anime
      score: -10000
