---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbitmanage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 1m
  target:
    name: qbitmanage-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: qbitmanage-configmap
            items:
              - key: config.yaml
  dataFrom:
    - extract:
        key: qbitmanage
      rewrite:
        - regexp:
            source: "(.*)"
            target: "QBITMANAGE_$1"

    - extract:
        key: notifiarr
        property: QBITMANAGE_API_KEY
      rewrite:
        - regexp:
            source: "(.*)"
            target: "NOTIFIARR_$1"
