---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-64k
allowVolumeExpansion: true
parameters:
  fstype: zfs
  poolname: speed
  recordsize: 64k
  compression: lz4
  dedup: off
  thinprovision: "yes"
  shared: "yes"
provisioner: zfs.csi.openebs.io
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-128k
allowVolumeExpansion: true
parameters:
  fstype: zfs
  poolname: speed
  recordsize: 128k
  compression: lz4
  dedup: off
  thinprovision: "yes"
  shared: "yes"
provisioner: zfs.csi.openebs.io
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfs-1m
allowVolumeExpansion: true
parameters:
  fstype: zfs
  poolname: speed
  recordsize: 1M
  compression: lz4
  dedup: off
  thinprovision: "yes"
  shared: "yes"
provisioner: zfs.csi.openebs.io
volumeBindingMode: Immediate
