# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/settings-schema.json

resource_providers:
  - name: custom-radarr
    type: custom-formats
    service: radarr
    path: /config/custom-formats/radarr

  - name: custom-sonarr
    type: custom-formats
    service: sonarr
    path: /config/custom-formats/sonarr
